### PR TITLE
Update Big Bang values and OSCAL types

### PR DESCRIPTION
**Pull request by lucasrod16**
Closes https://github.com/defenseunicorns/bigbang-oscal-component-generator/issues/5

***Note:*** There is a [follow-on issue](https://github.com/defenseunicorns/bigbang-oscal-component-generator/issues/10) to resolve remaining schema errors that this PR does not address.

- Updates OSCAL data types with auto-generated types with [go-oscal](https://github.com/defenseunicorns/go-oscal)

    - Since these types are generated directly from the OSCAL schema, this resolved most schema-related errors.

- Uses rfc3339 timestamp at `component-definition.metadata.last-modified` as specified by the [schema](https://github.com/usnistgov/OSCAL/blob/13bc85cbceb4fb5a05a9bbd9fbe5636c355c22e6/json/schema/oscal_component_schema.json#L1232)

- Updates party-uuids fields to be arrays

- Populates `component-definition.metadata.parties` with data

- Adds a function that generates UUIDs where needed. In this case, at `component-definition.uuid` and `component-definition.metadata.parties.uuid`

- Configures continuous integration with vulnerability scanning and OSCAL schema validation

### CODE REVIEW

**Comment by brandtkeller** [comment]
Pulling to test these changes. 

For transparency - there is a conversation in-progress around if aggregating components into a single component is valid schema/use-of-oscal OR if it could be valid OSCAL. 

Link: https://gitter.im/usnistgov-OSCAL/Lobby# (I don't see a method for grabbing specific conversations, but it's only a few threads old. 

That doesn't disclude this work from being useful and valid - so we can iterate as we learn more information.

**Comment by brandtkeller** [comment]
(noting this is in draft - will hold off for the moment)

**Comment by lucasrod16** [comment]
> For transparency - there is a conversation in-progress around if aggregating components into a single component is valid schema/use-of-oscal OR if it could be valid OSCAL.

Interesting. That's good information, thanks. I was hoping to get the tool to a place where it can be used in Big Bang CI for auto-magically generating the top-level OSCAL file. BB CI currently validates the [oscal-component.yaml](https://repo1.dso.mil/platform-one/big-bang/bigbang/-/blob/master/oscal-component.yaml) against [this schema](https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/), which is what I'm using to validate the changes here as well.

@brandtkeller Curious what your thoughts are on pursuing this further without more information on the validity of this method

**Comment by lucasrod16** [comment]
> (noting this is in draft - will hold off for the moment)

There are still some schema issues that need to be resolved. If/when I dive back into it, I'll make more detailed notes in this PR description about what they were

**Comment by brandtkeller** [comment]
@lucasrod16 After discussion with NIST - let's continue forward with that vision of the auto-magically generating the top-level OSCAL. 

Can you document where this lands prior to any gaps in implementation such that others can review and/or collaborate?

**Comment by lucasrod16** [comment]
> Can you document where this lands prior to any gaps in implementation such that others can review and/or collaborate?

Yes I can add update the `README` to include information on how it's meant to be used in BB CI

**Review by brandtkeller — APPROVED** [review]
No issues with implementation. Tested locally and reviewed pipelines.

**Pull request merged**
