### PR TITLE
Programatic retrieval of oscal components

### PR DESCRIPTION
**Pull request by mike-winberry**
Created git-extractor to pull the Git type out of components and addons of a provided interface in order to programmatically retrieve the oscal component yamls from their repos.

### CODE REVIEW

**Comment by mike-winberry** [comment]
Added some functionality to pull in the components without needing to write out all the names.

**Comment by RothAndrew** [comment]
I’m out of the office right now in the car. Go ahead and merge I Don’t want to block you for making progress

**Comment by RothAndrew** [comment]
Changes incorporated into #2

**Comment by RothAndrew** [comment]
@mike-winberry not deleting the branch in case you need it for something. Feel free to delete when you are ready.

**Pull request closed without merging**
